using FlowtrixAI.Application.Reports.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FlowtrixAI.Api.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class AiController(IAiService _aiService) : ControllerBase
    {
        /// <summary>
        /// Retrieves AI-generated insights for the current request.
        /// </summary>
        /// <remarks>This method is typically used as an API endpoint to obtain insights generated by the
        /// AI service. The response format and content depend on the implementation of the underlying AI
        /// service.</remarks>
        /// <returns>An <see cref="IActionResult"/> containing the generated insights data. The result is serialized as an HTTP
        /// response.</returns>
        [HttpGet("[action]")]
        public async Task<IActionResult> GetInsights()
        {
            var result = await _aiService.GenerateInsightsAsync();
            return Ok(result);
        }

    }
}
